/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;
import java.util.Collections;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./HW02-gradle/build/libs/Otus-0.1.jar
 *
 * To build:
 * ./gradlew build
 */
public class CollectionsOtus {
    public static void main(String... args) {
        int count = 31;
        Integer[] arr = new Integer[count];
        Arrays.fill(arr,0);
        DIYarrayList<Integer> list = new DIYarrayList<>();
        DIYarrayList<Integer> dist = new DIYarrayList<>();
        Collections.addAll(dist,arr);
        for (int k=0;k < arr.length;k++){
            arr[k]=k+10;
        }
        List<Integer> a = Arrays.asList(arr);
        Collections.reverse(a);
        Integer[]  b = new Integer[count];
        Collections.addAll(list,a.toArray(b));
        Collections.copy(dist,list);
        Collections.sort(dist,Comparator.comparing(Integer.class::cast));
        System.out.println("Welcome HomeWork02!!");


    }
}
