/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Lists;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./HW01-gradle/build/libs/Otus-0.1.jar
 *
 * To build:
 * ./gradlew build
 */
public class HelloOtus {
    public static void main(String... args) {
        ImmutableSet<Number> set;
        List<Integer> example = new ArrayList<>();
        int min = 0;
        int max = 100;
        for (int i = min; i < max; i++) {
            example.add(i % 10);
        }
        set = ImmutableSet.copyOf(Lists.reverse(example));
        System.out.println(set);
    }
}
